base_url = "https://beta7.io"

title       = "Beta7"
description = "The personal blog of Jesse Braham"

default_language = "en"

minify_html   = true
generate_feed = true

external_links_target_blank = true
external_links_no_follow    = true
external_links_no_referrer  = true

[markdown]
highlight_code  = true
highlight_theme = "one-dark"
render_emoji    = true

[extra]
author  = "Jesse Braham"
email   = "jesse@beta7.io"
github  = "jessebraham"
twitter = "notjessebraham"
